name: "Setup FlatBuffers Compiler (flatc)"
description: "Set up FlatBuffers compiler (flatc) for GitHub Actions workflows"
author: "Nugine"
branding:
  icon: "arrow-down"
  color: "white"

inputs:
  version:
    description: "The version of flatc to install"
    required: false
    default: "*"
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "dist/main.js"
